# Generated by Django 3.2.8 on 2021-12-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0002_rename_practitioners_practitioner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='school_interest',
            field=models.CharField(max_length=20),
        ),
    ]
