# Generated by Django 3.2.8 on 2021-12-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0004_alter_practitioner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='school_interest',
            field=models.CharField(choices=[('AK', 'Aikido'), ('BX', 'Boxing'), ('BJJ', 'Brazilian Juijitsu'), ('CP', 'Capoeira'), ('KA', 'Karate'), ('KM', 'Krav Maga'), ('KF', 'Kung Fu'), ('KB', 'KickBoxing'), ('MT', 'Muay Thai'), ('TKD', 'Tae Kwon Do'), ('VT', 'Vale Tudo'), ('WR', 'Wrestling')], default='', max_length=50, null=True, unique=True),
        ),
    ]
