# Generated by Django 3.2.8 on 2021-12-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school_interest',
            field=models.CharField(choices=[('Aikido', 'Aikido'), ('Boxing', 'Boxing'), ('BJJ', 'Brazilian Juijitsu'), ('Capoeira', 'Capoeira'), ('Karate', 'Karate'), ('KravMaga', 'Krav Maga'), ('KungFu', 'Kung Fu'), ('KickBoxing', 'KickBoxing'), ('MuayThai', 'Muay Thai'), ('TaeKwon Do', 'Tae Kwon Do'), ('ValeTudo', 'Vale Tudo'), ('Wrestling', 'Wrestling')], default='', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
