# Generated by Django 3.2.8 on 2021-12-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_interest',
            field=models.CharField(choices=[('Aikido', 'Aikido'), ('Boxing', 'Boxing'), ('BJJ', 'Brazilian Juijitsu'), ('Capoeira', 'Capoeira'), ('Karate', 'Karate'), ('KravMaga', 'Krav Maga'), ('KungFu', 'Kung Fu'), ('KickBoxing', 'KickBoxing'), ('MuayThai', 'Muay Thai'), ('TaeKwon Do', 'Tae Kwon Do'), ('ValeTudo', 'Vale Tudo'), ('Wrestling', 'Wrestling')], max_length=50, null=True, unique=True),
        ),
    ]
