# Generated by Django 3.2.8 on 2021-12-09 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_school_interest'),
        ('authentication', '0005_alter_user_address'),
    ]

    operations = [
    ]
