# Generated by Django 3.2.8 on 2021-12-09 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_type', models.CharField(choices=[('Aikido', 'Aikido'), ('Boxing', 'Boxing'), ('BJJ', 'Brazilian Juijitsu'), ('Capoeira', 'Capoeira'), ('Karate', 'Karate'), ('KravMaga', 'Krav Maga'), ('KungFu', 'Kung Fu'), ('KickBoxing', 'KickBoxing'), ('MuayThai', 'Muay Thai'), ('TaeKwon Do', 'Tae Kwon Do'), ('ValeTudo', 'Vale Tudo'), ('Wrestling', 'Wrestling')], default='', max_length=50, null=True, unique=True)),
                ('school_name', models.CharField(max_length=50)),
                ('school_address', models.CharField(max_length=50)),
                ('school_zip', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=12)),
                ('school_description', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('number_Reviews', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
