# Generated by Django 3.2.8 on 2021-12-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20211209_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='number_Reviews',
        ),
    ]
