# Generated by Django 3.2.8 on 2021-12-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Aikido', 'Aikido'), ('Boxing', 'Boxing'), ('BJJ', 'Brazilian Juijitsu'), ('Capoeira', 'Capoeira'), ('Karate', 'Karate'), ('KravMaga', 'Krav Maga'), ('KungFu', 'Kung Fu'), ('KickBoxing', 'KickBoxing'), ('MuayThai', 'Muay Thai'), ('TaeKwon Do', 'Tae Kwon Do'), ('ValeTudo', 'Vale Tudo'), ('Wrestling', 'Wrestling')], default='', max_length=50, null=True, unique=True),
        ),
    ]
