# Generated by Django 3.2.8 on 2021-12-08 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_school_school_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
