# Generated by Django 3.2.8 on 2021-12-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='school_id',
            field=models.ManyToManyField(related_name='rvw_school_name', to='schools.School'),
        ),
    ]
