# Generated by Django 3.2.8 on 2021-12-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='school_id',
            new_name='school_name',
        ),
    ]
